
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/renovatemateDB?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: coderslab
  mvc:
    staticPathPattern: /static/**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  web:
    resources:
      static-locations: classpath:/static/
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

server:
  servlet:
    encoding:
      force-request: true
      force-response: true
      charset: UTF-8
  compression:
    mime-types: application/javascript,text/css,text/html,application/xml

